global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'sui-monitoring'
    replica: 'prometheus-1'

rule_files:
  - "/etc/prometheus/rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
    scrape_interval: 5s
    metrics_path: /metrics

  - job_name: 'sui_bridge_mainnet'
    static_configs:
      - targets: ['host.docker.internal:9186']
        labels:
          service: 'sui_bridge'
          environment: 'mainnet'
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s
    honor_labels: true

  - job_name: 'sui_bridge_testnet'
    static_configs:
      - targets: ['host.docker.internal:9185']
        labels:
          service: 'sui_bridge'
          environment: 'testnet'
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s
    honor_labels: true
