global:
  resolve_timeout: 5m
  smtp_smarthost: localhost:587
  smtp_from: alertmanager@example.com
route:
  group_by:
  - alertname
  - service
  - environment
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 3h
  receiver: default
  routes:
  - match:
      severity: critical
    receiver: critical
    group_wait: 5s
    repeat_interval: 1h
  - match:
      severity: warning
    receiver: warning
    group_wait: 30s
    repeat_interval: 6h
receivers:
- name: default
  webhook_configs:
  - url: http://localhost:3001
    send_resolved: true
- name: critical
  webhook_configs:
  - url: http://localhost:3001
    send_resolved: true
  pagerduty_configs:
  - service_key: fab7643a487a440ad0cf569aa3ee1b75
    send_resolved: true
    description: '{{ .GroupLabels.alertname }} - {{ .CommonAnnotations.summary }}'
    severity: '{{ .CommonLabels.severity }}'
- name: warning
  webhook_configs:
  - url: http://localhost:3001
    send_resolved: true
inhibit_rules:
- source_match:
    severity: critical
  target_match:
    severity: warning
  equal:
  - alertname
  - service
  - environment
