groups:
- name: sui_bridge_common_alerts_Testnet_Bridge
  rules:
  - alert: SuiBridge_Uptime_Testnet_Bridge
    expr: increase(uptime{service="sui_bridge", environment="Testnet Bridge"}[10m])
      == 0
    for: 1m
    labels:
      severity: critical
      service: sui_bridge
      instance: '{{ $labels.instance }}'
      environment: '"Testnet Bridge"'
      alert_type: uptime
      bridge_index: '1'
      bridge_alias: Testnet Bridge
    annotations:
      summary: Critical uptime on { $labels.instance } (Testnet Bridge)
      description: The uptime for SUI Bridge Node instance { $labels.instance } (Testnet
        Bridge) has not increased in the last 10 minutes, suggesting a restart or
        failure.
      __dashboardUid__: ctles38bbprkmttbdkv0hijk
      __panelId__: '2'
  - alert: SuiBridge_MetricsPublicKeyAvailability_Testnet_Bridge
    expr: probe_success{service="sui_bridge_health_check", environment="Testnet Bridge"}
      == 0
    for: 2m
    labels:
      severity: critical
      service: sui_bridge
      instance: '{{ $labels.instance }}'
      environment: '"Testnet Bridge"'
      alert_type: metrics_public_key_availability
      bridge_index: '1'
      bridge_alias: Testnet Bridge
    annotations:
      summary: 'Metrics Public Key Unavailable (Instance: { $labels.instance }, Environment:
        Testnet Bridge)'
      description: The metrics public key endpoint for SUI Bridge Node instance {
        $labels.instance } (Testnet Bridge) is not accessible.
      __dashboardUid__: ctles38bbprkmttbdkv0hijk
      __panelId__: '2'
  - alert: SuiBridge_IngressAccess_Testnet_Bridge
    expr: probe_success{service="sui_bridge_ingress_check", environment="Testnet Bridge"}
      == 0
    for: 2m
    labels:
      severity: critical
      service: sui_bridge
      instance: '{{ $labels.instance }}'
      environment: '"Testnet Bridge"'
      alert_type: ingress_access
      bridge_index: '1'
      bridge_alias: Testnet Bridge
    annotations:
      summary: 'Bridge Ingress Unavailable (Instance: { $labels.instance }, Environment:
        Testnet Bridge)'
      description: The public ingress endpoint for SUI Bridge Node instance { $labels.instance
        } (Testnet Bridge) is not accessible.
      __dashboardUid__: ctles38bbprkmttbdkv0hijk
      __panelId__: '2'
  - alert: SuiBridge_VotingPower_Testnet_Bridge
    expr: current_bridge_voting_rights{service="sui_bridge", authority="${SUI_VALIDATOR}",
      environment="Testnet Bridge"} == 0
    for: 5m
    labels:
      severity: critical
      service: sui_bridge
      instance: '{{ $labels.instance }}'
      environment: '"Testnet Bridge"'
      alert_type: voting_power
      bridge_index: '1'
      bridge_alias: Testnet Bridge
    annotations:
      summary: 'Zero Bridge Voting Rights (Instance: { $labels.instance }, Environment:
        Testnet Bridge)'
      description: The SUI Bridge Node instance { $labels.instance } (Testnet Bridge)
        has zero voting rights, indicating a potential issue with the validator's
        authority.
      __dashboardUid__: ctles38bbprkmttbdkv0hijk
      __panelId__: '288'
- name: sui_bridge_client_disabled_alerts_Testnet_Bridge
  rules:
  - alert: SuiBridge_BridgeRequestErrors_Testnet_Bridge
    expr: increase(bridge_err_requests{service="sui_bridge", type="handle_sui_tx_digest",
      environment="Testnet Bridge"}[5m]) > 0
    for: 5m
    labels:
      severity: critical
      service: sui_bridge
      instance: '{{ $labels.instance }}'
      environment: '"Testnet Bridge"'
      alert_type: bridge_requests_errors
      bridge_index: '1'
      bridge_alias: Testnet Bridge
    annotations:
      summary: 'Bridge Request Errors Detected (Instance: { $labels.instance }, Environment:
        Testnet Bridge)'
      description: The SUI Bridge Node instance { $labels.instance } (Testnet Bridge)
        detected errors while handling SUI transaction digests in the last 5 minutes.
      __dashboardUid__: ctles38bbprkmttbdkv0hijk
      __panelId__: '294'
  - alert: SuiBridge_HighETHRPCLatency_Testnet_Bridge
    expr: bridge_eth_rpc_queries_latency{service="sui_bridge", environment="Testnet
      Bridge"} > 5000
    for: 5m
    labels:
      severity: critical
      service: sui_bridge
      instance: '{{ $labels.instance }}'
      environment: '"Testnet Bridge"'
      alert_type: bridge_high_latency
      bridge_index: '1'
      bridge_alias: Testnet Bridge
    annotations:
      summary: 'High ETH RPC Latency (Instance: { $labels.instance }, Environment:
        Testnet Bridge)'
      description: The ETH RPC queries latency for SUI Bridge Node instance { $labels.instance
        } (Testnet Bridge) is above 5 seconds.
      __dashboardUid__: ctles38bbprkmttbdkv0hijk
      __panelId__: '294'
  - alert: SuiBridge_HighCacheMisses_Testnet_Bridge
    expr: (rate(bridge_signer_with_cache_miss{service="sui_bridge", environment="Testnet
      Bridge"}[5m]) / (rate(bridge_signer_with_cache_hit{service="sui_bridge", environment="Testnet
      Bridge"}[5m]) + rate(bridge_signer_with_cache_miss{service="sui_bridge", environment="Testnet
      Bridge"}[5m]))) > 0.5
    for: 5m
    labels:
      severity: critical
      service: sui_bridge
      instance: '{{ $labels.instance }}'
      environment: '"Testnet Bridge"'
      alert_type: bridge_high_cache_misses
      bridge_index: '1'
      bridge_alias: Testnet Bridge
    annotations:
      summary: 'High Cache Miss Rate (Instance: { $labels.instance }, Environment:
        Testnet Bridge)'
      description: The cache miss rate for SUI Bridge Node instance { $labels.instance
        } (Testnet Bridge) is above 50%.
      __dashboardUid__: ctles38bbprkmttbdkv0hijk
      __panelId__: '305'
  - alert: SuiBridge_SUIRPCErrors_Testnet_Bridge
    expr: increase(bridge_sui_rpc_errors{service="sui_bridge", environment="Testnet
      Bridge"}[5m]) > 0
    for: 5m
    labels:
      severity: critical
      service: sui_bridge
      instance: '{{ $labels.instance }}'
      environment: '"Testnet Bridge"'
      alert_type: bridge_rpc_errors
      bridge_index: '1'
      bridge_alias: Testnet Bridge
    annotations:
      summary: 'SUI RPC Errors Detected (Instance: { $labels.instance }, Environment:
        Testnet Bridge)'
      description: SUI RPC errors detected for SUI Bridge Node instance { $labels.instance
        } (Testnet Bridge) in the last 5 minutes.
      __dashboardUid__: ctles38bbprkmttbdkv0hijk
      __panelId__: '322'
- name: sui_bridge_client_enabled_alerts_Testnet_Bridge
  rules:
  - alert: SuiBridge_LowGasBalance_Testnet_Bridge
    expr: bridge_gas_coin_balance{service="sui_bridge", environment="Testnet Bridge"}
      < 10000000000
    for: 1m
    labels:
      severity: critical
      service: sui_bridge
      instance: '{{ $labels.instance }}'
      environment: '"Testnet Bridge"'
      alert_type: low_gas_balance
      bridge_index: '1'
      bridge_alias: Testnet Bridge
    annotations:
      summary: 'Bridge Client Balance Running Low (Instance: { $labels.instance },
        Environment: Testnet Bridge)'
      description: Bridge Client Balance on { $labels.instance } (Testnet Bridge)
        is running out of tokens (below 10 SUI).
      __dashboardUid__: ctles38bbprkmttbdkv0hijk
      __panelId__: '316'
