groups:
- name: sui_bridge_alerts_Mainnet_Bridge
  rules:
  - alert: BridgeAlertFileReference_Mainnet_Bridge
    expr: vector(1)
    for: 0s
    labels:
      bridge_alias: Mainnet Bridge
      bridge_index: '0'
      alert_file: sui_bridge_0_mainnet_bridge_alerts.yml
    annotations:
      summary: Alert rules for Mainnet Bridge are loaded from sui_bridge_0_mainnet_bridge_alerts.yml
      description: This is a reference to the bridge-specific alert file for Mainnet
        Bridge
- name: sui_bridge_alerts_Testnet_Bridge
  rules:
  - alert: BridgeAlertFileReference_Testnet_Bridge
    expr: vector(1)
    for: 0s
    labels:
      bridge_alias: Testnet Bridge
      bridge_index: '1'
      alert_file: sui_bridge_1_testnet_bridge_alerts.yml
    annotations:
      summary: Alert rules for Testnet Bridge are loaded from sui_bridge_1_testnet_bridge_alerts.yml
      description: This is a reference to the bridge-specific alert file for Testnet
        Bridge
