apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://${PROMETHEUS_TARGET}
    isDefault: true
    uid: ctles38bbprkmttbdkv0
    editable: true
    jsonData:
      httpMethod: POST
      manageAlerts: true
      alertmanagerUid: alertmanager-datasource
      prometheusType: Prometheus
      prometheusVersion: 2.40.0
      cacheLevel: 'High'
      disableRecordingRules: false
      incrementalQueryOverlapWindow: 10m

  - name: Alertmanager
    type: alertmanager
    access: proxy
    url: http://${ALERTMANAGER_TARGET}
    uid: alertmanager-datasource
    editable: true
    jsonData:
      implementation: prometheus
      handleGrafanaManagedAlerts: true
